/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "CIS 4398 Fall 2022",
  "tagline": "Projects in Computer Science Capstone",
  "url": "https://undefined.github.io/",
  "baseUrl": "/undefined/",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "themes": [
    "@docusaurus/theme-live-codeblock"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/workspaces/project-instructors/documentation/sidebars.js",
          "routeBasePath": "docs",
          "path": "docs",
          "editUrl": "https://github.com/undefined/undefined/edit/main/documentation/",
          "remarkPlugins": [
            null
          ]
        },
        "theme": {
          "customCss": "/workspaces/project-instructors/documentation/src/css/custom.css"
        }
      }
    ],
    [
      "redocusaurus",
      {
        "specs": [
          {
            "id": "using-single-yaml",
            "spec": "static/openapi.yml.yaml",
            "route": "/api/"
          }
        ],
        "theme": {
          "customCss": "/workspaces/project-instructors/documentation/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "4398 Fall 2022",
      "logo": {
        "alt": "My Site Logo",
        "src": "https://upload.wikimedia.org/wikipedia/commons/1/17/Temple_T_logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "/tutorial/Intro",
          "label": "Docusaurus Tutorial",
          "position": "left",
          "activeBaseRegex": "/tutorial/"
        },
        {
          "href": "https://github.com/undefined/undefined",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "logo": {
        "alt": "My Site Logo",
        "src": "https://upload.wikimedia.org/wikipedia/commons/1/17/Temple_T_logo.svg"
      },
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Documentation",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/undefined/undefined"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 My Project, Inc. Built with Docusaurus.",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "imageZoom": {
      "selector": ".markdown img",
      "options": {
        "margin": 24,
        "zIndex": 100,
        "background": "white"
      }
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "tutorial",
        "path": "tutorial",
        "routeBasePath": "tutorial",
        "sidebarPath": "/workspaces/project-instructors/documentation/sidebars.js"
      }
    ],
    [
      "docusaurus2-dotenv",
      {
        "systemvars": true
      }
    ],
    "plugin-image-zoom"
  ],
  "scripts": [
    "https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
