# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Export PDF Docs

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Deploy Docs"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Prince
      run: |
        curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
        tar zxf prince-14.2-linux-generic-x86_64.tar.gz
        cd prince-14.2-linux-generic-x86_64
        yes "" | sudo ./install.sh

    - name: Build PDF
      run: npx docusaurus-prince-pdf -u https://capstone-projects-2022-fall.github.io/project-instructors/docs/intro --output docs.pdf

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: result
        # The output filename can be specified with --output option
        path: docs.pdf
        if-no-files-found: error

    # ...other steps

